"""
Django settings for medic project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0j!!%+2eah%xwg^j#fir_+a7sm6bwzg72++-v4^zvxo!q*650x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'channels',
    'drf_spectacular',

    'accounts',
    'monitoring',
    'medication',
    'alerts',
    'communication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'EXCEPTION_HANDLER': 'medic.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'MEDIC API',
    'DESCRIPTION': (
        "## MEDICAL SAFETY NOTICE\n"
        "This system is a prototype clinical decision-support notification tool, NOT a diagnostic system. "
        "Outputs such as risk indicators, vital threshold alerts, and wound analysis are decision-support "
        "heuristics and are NOT clinically validated diagnostic findings. They are designed exclusively to "
        "prompt clinical review by the assigned healthcare team.\n\n"
        "## Timezone & Timestamps\n"
        "All timestamps across the API and database are timezone-aware and localized to Asia/Kolkata (IST).\n\n"
        "## Authorization & Privacy Model\n"
        "All patient-scoped endpoints enforce strict ownership and doctor-patient assignment checks. "
        "To avoid disclosing patient existence or confirming resource records to unauthorized callers, "
        "unauthorized access attempts return HTTP 404 Not Found (rather than 403 Forbidden).\n\n"
        "## Global Authentication\n"
        "All protected endpoints require Bearer JWT authentication via the HTTP Authorization header:\n"
        "`Authorization: Bearer <access_token>`\n\n"
        "- Obtain token pair: `POST /api/token/` with `{\"username\": ..., \"password\": ...}`\n"
        "- Refresh access token: `POST /api/token/refresh/` with `{\"refresh\": ...}`\n\n"
        "## Real-Time WebSocket Channels\n"
        "WebSockets authenticate via JWT passed as a query string parameter (`?token=<jwt_access_token>`). "
        "Connections without valid tokens close with code 4401. Unauthorized role or non-participant connections close with code 4403.\n\n"
        "1. **Doctor Alerts Channel**: `ws/alerts/?token=<token>`\n"
        "   - Target: Authenticated doctors with active DoctorProfile.\n"
        "   - Channel Group: `doctor_<doctor_user_id>_alerts`\n"
        "   - Dispatched events: Vital threshold alerts, medication missed dose alerts, and new patient chat message alerts.\n"
        "   - Payload format:\n"
        "     ```json\n"
        "     {\n"
        "       \"id\": 12,\n"
        "       \"patient_id\": 3,\n"
        "       \"patient_display_name\": \"Jane Doe\",\n"
        "       \"severity\": \"high\",\n"
        "       \"message\": \"High fever detected: 39.5 C\",\n"
        "       \"created_at\": \"2026-03-24T10:00:00+05:30\"\n"
        "     }\n"
        "     ```\n\n"
        "2. **Patient Notifications Channel**: `ws/notifications/?token=<token>`\n"
        "   - Target: Authenticated patients with active PatientProfile.\n"
        "   - Channel Group: `patient_<patient_profile_id>_notifications`\n"
        "   - Dispatched events: Scheduled medication dose reminders and new doctor chat messages.\n"
        "   - Payload format:\n"
        "     ```json\n"
        "     {\n"
        "       \"type\": \"medication_reminder\",\n"
        "       \"dose_id\": 45,\n"
        "       \"medicine_name\": \"Amoxicillin\",\n"
        "       \"dosage\": \"500mg\",\n"
        "       \"scheduled_time\": \"08:00 PM\",\n"
        "       \"message\": \"Time for Amoxicillin (500mg) at 08:00 PM.\",\n"
        "       \"created_at\": \"2026-03-24T19:55:00+05:30\"\n"
        "     }\n"
        "     ```\n\n"
        "3. **Doctor-Patient Chat Channel**: `ws/chat/<conversation_id>/?token=<token>`\n"
        "   - Target: Authenticated doctor or patient participating in the active conversation.\n"
        "   - Channel Group: `chat_<conversation_id>`\n"
        "   - Messages sent/received:\n"
        "     ```json\n"
        "     {\n"
        "       \"id\": 101,\n"
        "       \"conversation_id\": 1,\n"
        "       \"sender_id\": 2,\n"
        "       \"sender_name\": \"Dr. John Smith\",\n"
        "       \"sender_role\": \"doctor\",\n"
        "       \"content\": \"How is your incision healing today?\",\n"
        "       \"is_read\": false,\n"
        "       \"created_at\": \"2026-03-24T10:15:00+05:30\"\n"
        "     }\n"
        "     ```\n\n"
        "## Lovable Frontend Integration Guide\n"
        "- **Base API URL**: `http://<backend-host>:8000/api/`\n"
        "- **Default Headers**: `Authorization: Bearer <access_token>`, `Content-Type: application/json` (except file uploads which use `multipart/form-data`)\n"
        "- **WebSocket Base**: `ws://<backend-host>:8000/` (use `wss://` in production with TLS)\n"
        "- **CORS Notice**: Full CORS configuration is scheduled for Phase 8. When developing the Lovable frontend separately, configure a development proxy or enable cross-origin headers during local testing."
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    # NOTE: In development Swagger UI is accessible publicly.
    # Restrict to ['rest_framework.permissions.IsAdminUser'] before deploying to production.
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

import sys
import os

if 'test' in sys.argv:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]

ASGI_APPLICATION = "medic.asgi.application"

REDIS_URL = os.environ.get("REDIS_URL")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }