"""
Alerts Generation Service.

MEDICAL SAFETY NOTICE:
Alerts generated by this service are prototype decision-support notifications,
NOT diagnostic findings. They are threshold-based indicators designed to prompt
clinical review by the assigned healthcare team.
"""
import logging
from .models import Alert
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

logger = logging.getLogger(__name__)


def analyze_health_log(log):
    """
    Evaluates health log vitals against prototype decision-support thresholds.
    Creates Alert records and dispatches real-time WebSocket notifications.
    
    NOTE FOR PHASE 5:
    Currently broadcasts to global group "doctor_alerts".
    Phase 5 will replace this with targeted dispatch to the patient's assigned doctor (doctor_<id>_alerts).
    """
    alerts_to_create = []

    if log.temperature is not None:
        if log.temperature > 39.0:
            alerts_to_create.append(
                ("Urgent medical review recommended: high temperature recorded (prototype indicator)", "high")
            )
        elif log.temperature > 38.0:
            alerts_to_create.append(
                ("Medical review recommended: elevated temperature recorded (prototype indicator)", "high")
            )

    if log.pain_level is not None:
        if log.pain_level > 9:
            alerts_to_create.append(
                ("Urgent review recommended: severe pain reported (prototype indicator)", "high")
            )
        elif log.pain_level > 8:
            alerts_to_create.append(
                ("Medical review recommended: notable pain reported (prototype indicator)", "medium")
            )

    if not log.medication_taken:
        alerts_to_create.append(
            ("Medication adherence notice: scheduled dose not recorded (prototype indicator)", "low")
        )

    channel_layer = get_channel_layer()

    created_alerts = []
    for message, severity in alerts_to_create:
        alert = Alert.objects.create(
            patient=log.patient,
            message=message,
            severity=severity
        )
        created_alerts.append(alert)

        # Broadcast via Channel layer if available
        if channel_layer:
            try:
                # Dispatches to "doctor_alerts" group (Phase 5 will isolate this per-doctor)
                async_to_sync(channel_layer.group_send)(
                    "doctor_alerts",
                    {
                        "type": "send_alert",
                        "patient_id": log.patient.id,
                        "message": message,
                        "severity": severity,
                    }
                )
            except Exception as e:
                logger.error(f"Failed to dispatch alert over WebSocket: {e}")

    return created_alerts
