"""
Alerts Generation Service.

MEDICAL SAFETY NOTICE:
Alerts generated by this service are prototype decision-support notifications,
NOT diagnostic findings. They are threshold-based indicators designed to prompt
clinical review by the assigned healthcare team.
"""
import logging
from django.db import transaction
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from .models import Alert

logger = logging.getLogger(__name__)


def dispatch_alert_to_doctor(doctor_id, payload):
    """
    Delivers an alert payload strictly to doctor_<doctor_id>_alerts.
    Safely wraps channel-layer calls in try/except with logging so a delivery
    failure never causes calling requests to fail.
    Never logs sensitive health data or credentials.
    """
    if not doctor_id:
        return

    try:
        channel_layer = get_channel_layer()
        if channel_layer:
            async_to_sync(channel_layer.group_send)(
                f"doctor_{doctor_id}_alerts",
                {
                    "type": "send_alert",
                    **payload
                }
            )
    except Exception as e:
        logger.error(f"WebSocket delivery failure in alert dispatch: {type(e).__name__}")


def analyze_health_log(log):
    """
    Evaluates health log vitals against prototype decision-support thresholds.
    Creates Alert records and dispatches real-time WebSocket notifications strictly
    to the patient's assigned doctor's group (doctor_<doctor_id>_alerts).

    Skips cleanly with no error when the patient has no assigned doctor.
    Broadcast payload contains only: alert id, patient_id, patient display name,
    severity, message, created_at (no raw vitals).
    
    Wrapped in transaction.on_commit so an alert is never broadcast for a database
    write that gets rolled back.
    """
    alerts_to_create = []

    if log.temperature is not None:
        if log.temperature > 39.0:
            alerts_to_create.append(
                ("Urgent medical review recommended: high temperature recorded (prototype indicator)", "high")
            )
        elif log.temperature > 38.0:
            alerts_to_create.append(
                ("Medical review recommended: elevated temperature recorded (prototype indicator)", "high")
            )

    if log.pain_level is not None:
        if log.pain_level > 9:
            alerts_to_create.append(
                ("Urgent review recommended: severe pain reported (prototype indicator)", "high")
            )
        elif log.pain_level > 8:
            alerts_to_create.append(
                ("Medical review recommended: notable pain reported (prototype indicator)", "medium")
            )

    if not log.medication_taken:
        alerts_to_create.append(
            ("Medication adherence notice: scheduled dose not recorded (prototype indicator)", "low")
        )

    patient = log.patient
    doctor_id = patient.doctor_id
    patient_display_name = patient.user.get_full_name() or patient.user.username

    created_alerts = []
    for message, severity in alerts_to_create:
        alert = Alert.objects.create(
            patient=patient,
            message=message,
            severity=severity
        )
        created_alerts.append(alert)

        # Only dispatch if patient has an assigned doctor; skip cleanly otherwise
        if doctor_id:
            payload = {
                "alert_id": alert.id,
                "id": alert.id,
                "patient_id": patient.id,
                "patient_display_name": patient_display_name,
                "severity": severity,
                "message": message,
                "created_at": alert.created_at.isoformat(),
            }
            # Wrap broadcast in on_commit to prevent leaks on rollback
            transaction.on_commit(
                lambda d_id=doctor_id, p=payload: dispatch_alert_to_doctor(d_id, p)
            )

    return created_alerts
