# Generated by Django 6.0.3 on 2026-09-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='taken_status',
            field=models.BooleanField(default=False, help_text='Legacy summary flag. Use related MedicationDose records for daily adherence.'),
        ),
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True, help_text='Timezone-aware scheduled dose datetime')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed')], db_index=True, default='pending', max_length=10)),
                ('taken_at', models.DateTimeField(blank=True, help_text='Exact timestamp when the patient recorded taking this dose', null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the ~30-min reminder was dispatched to the patient', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='medication.medication')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'constraints': [models.UniqueConstraint(fields=('medication', 'scheduled_for'), name='unique_medication_scheduled_dose')],
            },
        ),
    ]
