# Generated by Django 6.0.3 on 2026-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthlog',
            name='recovery_score',
            field=models.IntegerField(default=100),
        ),
    ]
