# Generated by Django 6.0.3 on 2026-09-21 17:55

import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_dailyhealthlog_recovery_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyhealthlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='woundimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='woundimage',
            name='image',
            field=models.ImageField(upload_to=monitoring.models.wound_image_upload_path),
        ),
    ]
